version: '3.9'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    networks:
      - kafkazoo
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - kafkazoo
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  kafka-producer-app:
    container_name: kafka_producer_app
    build:
      context: ./kafka_components
      dockerfile: Dockerfile_kafka_app
    networks:
      - kafkazoo
    depends_on:
      - kafka

  spark:
    container_name: spark
    build:
      context: ./spark
      dockerfile: Dockerfile_spark
    hostname: spark_master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - kafkazoo
    depends_on:
      - kafka

  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile_spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no  
    networks:
      - kafkazoo
    depends_on:
      - spark

  spark-app:
    build:
      context: ./app
      dockerfile: Dockerfile_app
    networks:
      - kafkazoo
    depends_on:
      - kafka
      - spark

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: 'on-failure'
    ports:
      - "27017:27017"
    networks:
      - kafkazoo
    environment:
      - MONGO_INITDB_DATABASE=sentiment_analysis
    env_file:
      - .env_mongo
    volumes:
      - mongodata:/data/db
    depends_on:
      - spark-app

  streamlit:
    container_name: streamlit
    build:
      context: ./dashboard
      dockerfile: Dockerfile_dashboard
    ports:
      - "8501:8501"
    networks:
      - kafkazoo
    depends_on: 
      - mongo

networks:
  kafkazoo:
    driver: bridge

volumes:
  mongodata: