version: '3.9'

networks:
  kafkazoo:
    driver: bridge
    attachable: true

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    networks:
      - kafkazoo
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - kafkazoo
    volumes:
      - shared-workspace:/opt/workspace
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  kafka-producer-app:
    container_name: kafka_producer_app
    build:
      context: ./kafka_components
      dockerfile: Dockerfile_kafka_app
    networks:
      - kafkazoo
    ports:
      - "80:80"
    depends_on:
      - kafka

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - kafkazoo

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - kafkazoo
    depends_on:
      - spark

  spark-app:
    build:
      context: ./app
      dockerfile: Dockerfile_app
    networks:
      - kafkazoo
    depends_on:
      - kafka

  mongo:
      # Official image from Docker Hub: https://hub.docker.com/_/mongo 
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=sentiment_analysis
    restart: always
    ports:
      - 27017:27017
    networks:
      - kafkazoo
    depends_on:
      - spark-app

  streamlit:
      container_name: streamlit
      build:
        context: ./dashboard
        dockerfile: Dockerfile_dashboard
      ports:
        - "8501:8501"
      networks:
        - kafkazoo
      depends_on: 
        - mongo