version: '3.9'

services:
    kafka:
        container_name: kafka
        build:
            context: .
            dockerfile: kafka_components/Dockerfile_kafka
        ports:
           - "9092:9092"
    spark:
        container_name: spark
        build:
            context: .
            dockerfile: app/Dockerfile_app
    mongodb:
         container_name: mongo
         image: mongo
         restart: always
         ports:
             - "27017:27017"
         environment:
             MONGO_INITDB_ROOT_USERNAME: root
             MONGO_INITDB_ROOT_PASSWORD: example
    streamlit:
        container_name: streamlit
        build:
            context: .
            dockerfile: dashboard/Dockerfile_dashboard
        ports:
            - "80:80"