version: '3.9'

services:
    producer: 
        build: 
            context: .
            dockerfile: app/Dockerfile_producer
    app:
        build: 
            context: .
            dockerfile: app/Dockerfile_app
    bd:
        build:
             context: .
             dockerfile: bd/Dockerfile_mongo
    dashboard:
        build:
            context: .
            dockerfile: dashboard/Dockerfile_dashboard