FROM python:3.10.7-slim-bullseye

EXPOSE 8501

WORKDIR /home/user/dashboard

COPY . .

RUN pip install -r requirements.txt

ENTRYPOINT ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]