FROM ubuntu:latest

WORKDIR /home/user/dashboard

COPY . .

RUN apt-get update &&\
    apt-get install -y python3 python3-pip &&\
    pip install -r requirements.txt

ENTRYPOINT ["streamlit", "run", "dashboard.py"]