FROM ubuntu:20.04

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/

WORKDIR /home/user/app

COPY . .

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update &&\
    apt-get install openjdk-8-jdk -y &&\
    apt-get install -y python3.10 python3-pip &&\
    pip install -r requirements.txt &&\
    apt-get install -y software-properties-common &&\
    add-apt-repository ppa:deadsnakes/ppa&&\
    export JAVA_HOME &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

ENV PYSPARK_PYTHON python3
ENV PYSPARK_DRIVER_PYTHON python3

ENTRYPOINT ["python3", "app.py"]
