FROM ubuntu:latest


RUN apt-get update &&\
    apt-get install -y python3 &&\
    apt-get install python3-pip -y &&\
    pip install -r config/requirements.txt

WORKDIR /home/user/
COPY . .

ENTRYPOINT ["python3", "./producer.py"]


