FROM python:3.9
# Official image from Docker Hub: https://hub.docker.com/_/ubuntu

WORKDIR /home/user/kafka_components
COPY . .

RUN pip install -r requirements.txt

ENTRYPOINT ["python3", "producer.py"]
